const APP_TITLE = "Pixel Desktop Pet World";
const MAX_PETS = 3;
const OVERLAY_HEIGHT = 132;
const PANEL_WIDTH = 620;
const PANEL_HEIGHT = 820;
const PET_SIZE = 92;
const WORLD_TICK_MS = 100;
const WORLD_SIDE_PADDING = 18;
const MIN_PET_SPACING = 64;
const SCENE_PET_FLOOR = 6;
const SLOGAN_MIN_DELAY_MS = 5000;
const SLOGAN_MAX_DELAY_MS = 10000;

module.exports = {
  APP_TITLE,
  MAX_PETS,
  OVERLAY_HEIGHT,
  PANEL_WIDTH,
  PANEL_HEIGHT,
  PET_SIZE,
  WORLD_TICK_MS,
  WORLD_SIDE_PADDING,
  MIN_PET_SPACING,
  SCENE_PET_FLOOR,
  SLOGAN_MIN_DELAY_MS,
  SLOGAN_MAX_DELAY_MS
};
